function biography() {
	var headerHTML = "<h2>william shakespeare</h2>";
	var paragraph1 = "<p> William Shakespeare, known affectionately worldwide as The Eternal Bard, was baptized on the 26th of April, 1564 in Stratford-upon-Avon, England. Born to John Shakespeare and  Mary Arden, an alderman and a daughter of an affluent farmer, Shakespeare was born to a well-off family, offering him a financial base to launch his career from. He was was educated at the King's New School in Stratford, a grammar school, which, at the time, was the equivalent of a modern and high-class college. At the age of 18, he was married to Anne Hathaway, a woman 8 years his senior in 1583. Just one year later, she gave birth to their first daughter, Susanna. The year later Anne bore fraternal twins named Judith and Hamnet, the latter of which sadly passed away at the age of 11.</p>";
	var paragraph2 = "<p> William Shakespeare is known internationally as one of the best playwrights the world has ever seen, penning the epic tragedies Romeo and Juliet, Macbeth, comedies such as A Midsummer Night's Dream, and many others. Shakespeare's fame for writing poetry is also widespread as well, having written 154 sonnets, two long narrative poems, three epitaphs on different people, and a large amount of assorted poetry. As a poet, he is most famous for his 154 sonnets, the most noted of which are Sonnet 18, bearing the famous line: 'Shall I compare thee to a summer's day?'; Sonnet 130, being a comical poem about a mistress written in everyday language ('My mistress' eyes are nothing like the sun,'); the prologue to Romeo and Juliet: 'Two houses, both alike in dignity...'; and the Dark Lady poem series, comprised of sonnets 127 through 152. His sonnets mostly revolved around a core of two themes: love and beauty. These popular themes, with variations such as the dangers of love (e.g. sonnet 116) and real vs. cliché beauty (e.g. sonnet 130) which helped to increase and sustain his large following. </p>";
	var paragraph3 = "<p> Shakespeare's sonnets stood out from the other type of sonnet present at the time: the Italian petrarchan sonnet. While both of these sonnets had many similarities, such as having 14 lines and being set in iambic pentameter, Shakespeare's sonnets represented a break from the mold set out by Francisco Petrarch. For example, Shakespearean sonnets held a simple rhyme scheme of ABABCDCDEFEFGG, or three quatrains and a rhyming couplet. Petrarch, however, had a more stylistic scheme of ABBAABBACDCDCD, a section of eight lines (an octave) and a section of six lines (a sextet) From the difference in rhyme scheme, one can see the difference in poem division as well. Shakespeare's sonnets were quite simple, and almost the entire poem, save for the rhyming couplet, remained on a single, consistent topic, and the final couplet was just a simple contrast or shift in tone. Petrarch's sonnets were divided into two parts: the first eight lines (the octave) and the final six lines (the sextet). Whilst the poem was on one topic, the octave and the sextet were quite different, as the sextet served as a volta, or a turn. This turn changed the perspective or view of the poem to a different one from the octave, creating a shift in mood, tone or stance of the poem. These differences, and many more, were quite significant, and the more accessible style of Shakespearean sonnet allowed it to be the more popular type, and the kind of which more people associate a sonnet with. </p>";
	var paragraph4 = "<p> His poems have achieved universal acclaim, countless fragments of which have been used and reused throughout the world, from movie scripts to courting lines to everyday language. Shakespeare shuffled off his mortal coil (to take from Hamlet's famous monologue) on the 23rd of April, 1616. He was interred at the Holy Trinity Church in his hometown of Stratford-upon-Avon two days later. He left behind a legacy of poetry and prose that have been, and forever will be, admired by everyone on the four corners of the planet.</p>";
	var tombstoneInscription = "<p> These words were inscribed on his tombstone: <em><br /> Good friend for Jesus' sake forbear<br />To dig the dust enclosed here!<br />Blessed be the man that spares these stones,<br />And curst be he who moves my bones.</em></p>";
	var bibliography = "<h3> bibliography: </h3> <p> AbsoluteShakespeare.com. 2005. <em>Shakespeare Biography</em> [online] Available from: <a href = 'http://absoluteshakespeare.com/trivia/biography/shakespeare_biography.htm'> http://absoluteshakespeare.com/trivia/biography/shakespeare_biography.htm </a> [Accessed 23 November 2012]</p> <p> Academy of American Poets, 2012. <em>Poetic Form: Sonnet</em> [online] Available from: <a href = 'http://www.poets.org/viewmedia.php/prmMID/5791'> http://www.poets.org/viewmedia.php/prmMID/5791 </a> [Accessed 27 November 2012]</p> <p> Andrews, J., 1987. <em>William Shakespeare</em> [online] Available from: <a href ='http://people.brandeis.edu/~teuber/shakespearebio.html'>http://people.brandeis.edu/~teuber/shakespearebio.html </a> [Accessed 26 November 2012]</p> <p> The Biography Channel website. 2012. <em>William Shakespeare</em> [online] Available from: <a href = 'http://www.biography.com/people/william-shakespeare-9480323'> http://www.biography.com/people/william-shakespeare-9480323 </a> [Accessed 23 November 2012]</p> <p> Sparknotes, LLC. 2012. <em>Shakespeare's Sonnets.</em> [online] Available from: <a href = 'http://www.sparknotes.com/shakespeare/shakesonnets/themes.html'> http://www.sparknotes.com/shakespeare/shakesonnets/themes.html </a> [Accessed 24 November 2012] </p>";
	document.getElementById('heading').innerHTML = headerHTML;
	document.getElementById('contentArea').innerHTML = paragraph1 + paragraph2 + paragraph3 + paragraph4 + tombstoneInscription + bibliography;
}


function sonnet116() {
	var headerHTML = "<h2>sonnet 116</h2>";
	var poemHTML = "<p>Let me not to the marriage of true minds</p> <p>Admit impediments. Love is not love</p> <p>Which alters when it alteration finds,</p> <p>Or bends with the remover to remove:</p> <p>O no! it is an ever-fixed mark</p> <p>That looks on tempests and is never shaken;</p> <p>It is the star to every wandering bark,</p> <p>Whose worth's unknown, although his height be taken.</p> <p>Love's not Time's fool, though rosy lips and cheeks</p> <p>Within his bending sickle's compass come:</p> <p>Love alters not with his brief hours and weeks,</p> <p>But bears it out even to the edge of doom.</p> <p>If this be error and upon me proved,</p> <p>I never writ, nor no man ever loved.</p>";
	document.getElementById('heading').innerHTML = headerHTML;
	document.getElementById('contentArea').innerHTML = poemHTML;
}


function sonnet130() {
	var headerHTML = "<h2>sonnet 130</h2>";
	var poemHTML = "<p>My mistress' eyes are nothing like the sun,</p> <p>Coral is far more red than her lips' red,</p> <p>If snow be white, why then her breasts are dun,</p> <p>If hair be wires, black wires grow on her head.</p> <p>I have seen roses damasked, red and white,</p> <p>But no such roses see I in her cheeks;</p> <p>And in some perfumes is there more delight</p> <p>Than in the breath that from my mistress reeks.</p> <p>I love to hear her speak, yet well I know</p> <p>That music hath a far more pleasing sound;</p> <p>I grant I never saw a goddess go;</p> <p>My mistress when she walks treads on the ground.</p> <p>And yet, by heaven, I think my love as rare</p> <p>As any she belied with false compare.</p>";
	document.getElementById('heading').innerHTML = headerHTML;
	document.getElementById('contentArea').innerHTML = poemHTML;
}

function sonnet130analysis() {
	var headerHTML = "<h2>sonnet 130 - analysis</h2>";
	var paragraph1 = "<p><em>Sonnet 130, by William Shakespeare, published in the late 16th century, is an example of a Shakespearean sonnet, created by the Bard himself.</em></p>";
	var paragraph2 = "<p> As the poem was written in the late 16th century, the language of the poem is very traditional, with literary language and proper grammar seen throughout the Sonnet. Words like 'damask'd' and 'dun' are used in the poem, yet the overall wording of the Sonnet is accessible to modern readers, due to the simplicity of the language utilized in the rest of the poem, resembling today's colloquial speech and writing.</p>";
	var paragraph3 = "<p> As it is a Shakespearean sonnet, the poem is composed of 14 lines, organized into three quatrains and a final rhyming couplet. Each line conforms to the iambic pentameter measure. As with all sonnets, the rhyme alternates every second line save for the final two lines, which form a rhyming couplet. </p>"; 
	var paragraph4 = "<p> Sonnet 130 is based around the author's description of the subject, focusing on her features, which, through the author's words, are less than ideal. Throughout the single-stanza poem he compares her to majestic objects: he says that 'her eyes are nothing like the sun', coral has a richer color than her lips, her hair being as cluttered as 'black wires' and other derogatory remarks. This perceived insulting of his mistress is suddenly nullified by the final couplet, through a change in the tone. Despite describing his woman as being inferior through comparisons to aesthetically pleasing features beautiful women may have, he remarks her as being as lovely as any woman. He accomplishes this without making any false comparisons, such as saying 'her voice is as lyrical and wonderful as music', in contrast to the other poets of that time. </p>";
	var paragraph5 = "<p> The main poetic device present in this sonnet is the usage of comparisons through similes and metaphors, visible in almost every line. In the first segment of four lines, her facial features, her eyes and her lips, are compared to the sun and coral, respectively. The second quartet focuses on scent and her cheeks, contrasted with scented perfumes and richly-coloured roses. In the final quartet, her walking and voice are deemed inferior to the stride of a goddess and the sound of music. In the concluding couplet, however, the author takes a sudden change in his tone: rather than continue the deriding remarks against his mistress, he says that he still loves her for who she is, and he doesn't need to make hyperbolic statement to prove it. Through the use of this poetic device, the theme can be ascertained: the people you love don't have to be perfect aesthetically, rather, they should be able to please you with their personality and their presence without having to be over-the-top.</p>";
	var paragraph6 = "<p> The poem is written in a mocking tone for the majority of the sonnet; the colloquial language conveys the lack of aesthetic beauty his mistress has in comparison to the more 'beautiful' objects. The shift in tone from the author to appreciating his mistress is also accompanied by a change in language to a more literary style, representative of the poems of that age. </p>";
	document.getElementById('heading').innerHTML = headerHTML;
	document.getElementById('contentArea').innerHTML = paragraph1 + paragraph2 + paragraph3 + paragraph4 + paragraph5 + paragraph6;
}
